language: python
cache:
  - pip
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - python setup.py -q install
  - pip install sphinx
stages:
  - build
  - test
  - dist
jobs:
  include:
    - stage: "build"
      name: "Build package"
      script: python setup.py build

    - stage: "test"
      name: "Test suite"
      script: python setup.py test

    - stage: "dist"
      name: "Build release"
      script:
        - python setup.py bdist
        - python setup.py sdist
        - python setup.py bdist_wheel

after_success:
  - bash <(curl -s https://codecov.io/bash)
branches:
  only:
    - master
