language: python
cache:
  - pip
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - python setup.py -q install
  - pip install sphinx
script:
  - python setup.py build
  - python setup.py test

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - master
    - /^v\d+\..*/

stages:
  - test
  - deploy

jobs:
  include:
    - stage: test
      name: "Code Quality"
      dist: trusty
      language: java
      install: skip
      script: sonar-scanner -Dsonar.projectVersion=$TRAVIS_TAG
      addons:
        sonarcloud:
          organization: "bontiv-github"
          token: $SONAR_TOKEN

    - stage: deploy
      name: Deployment
      script: python setup.py sdist bdist bdist_wheel
      deploy:
        - provider: releases
          api_key: $GITHUB_OAUTH_TOKEN
          file_glob: true
          file: "dist/*"
          skip_cleanup: true
          prerelease: true
          on:
            tags: true
            condition: $TRAVIS_TAG =~ ^v.*dev.*$

        - provider: releases
          api_key: $GITHUB_OAUTH_TOKEN
          file_glob: true
          file: "dist/*"
          skip_cleanup: true
          on:
            tags: true
            condition: $TRAVIS_TAG =~ ^v[0-9.]*$

        - provider: pypi
          distributions: "sdist bdist_wheel"
          user: "bontiv"
          password: $PYPI_PASSWORD
          server: https://test.pypi.org/legacy/
          on:
            tags: true

        - provider: pypi
          distributions: "sdist bdist_wheel"
          user: "bontiv"
          password: $PYPI_PASSWORD
          on:
            tags: true
            condition: $TRAVIS_TAG =~ ^v[0-9.]*$

      if: tag IS present

before_deploy:
  - python setup.py bdist
  - python setup.py sdist
  - python setup.py bdist_wheel
