language: python
cache:
  - pip
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install --upgrade pip setuptools pytest pytest-cov
  - python setup.py -q install
script:
  - pytest --cov-branch --cov=./ --cov-report=xml:coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

branches:
  only:
    - master
    - /^v\d+\..*/

stages:
  - test
  - docs
  - deploy

jobs:
  include:
    - stage: test
      name: "Code Quality"
      dist: trusty
      language: java
      before_install:
        - sudo apt-get install -qq python3 python3-pip python3-pytest pylint
      install:
        - pip3 install --upgrade --user pip setuptools pytest pytest-cov
        - python3 setup.py -q install --user
      script:
        - python3 -m pytest --cov-branch --cov=./ --cov-report=xml:coverage.xml
        - sonar-scanner -Dsonar.projectVersion=$TRAVIS_TAG
      addons:
        sonarcloud:
          organization: "bontiv-github"
          token: $SONAR_TOKEN

    - stage: docs
      name: Documentation
      install:
        - python setup.py -q install
        - pip install -r docs/requirements.txt
      script: python setup.py build_docs
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_OAUTH_TOKEN
        local-dir: build/html
        on:
          branch: master

    - stage: docs
      name: Documentation coverage
      install:
        - pip install -r docs/requirements.txt
      script: make -C docs/ coverage

    - stage: deploy
      name: Deployment
      script: python setup.py sdist bdist bdist_wheel
      deploy:
        - provider: releases
          api_key: $GITHUB_OAUTH_TOKEN
          file_glob: true
          file: "dist/*"
          skip_cleanup: true
          prerelease: true
          on:
            tags: true
            condition: $TRAVIS_TAG =~ ^v.*dev.*$

        - provider: releases
          api_key: $GITHUB_OAUTH_TOKEN
          file_glob: true
          file: "dist/*"
          skip_cleanup: true
          on:
            tags: true
            condition: $TRAVIS_TAG =~ ^v[0-9.]*$

        - provider: pypi
          distributions: "sdist bdist_wheel"
          user: "bontiv"
          password: $PYPI_PASSWORD
          server: https://test.pypi.org/legacy/
          on:
            tags: true

        - provider: pypi
          distributions: "sdist bdist_wheel"
          user: "bontiv"
          password: $PYPI_PASSWORD
          on:
            tags: true
            condition: $TRAVIS_TAG =~ ^v[0-9.]*$

      if: tag IS present

before_deploy:
  - python setup.py bdist
  - python setup.py sdist
  - python setup.py bdist_wheel
